-- +goose Up
CREATE TABLE IF NOT EXISTS accounts(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying(255) NOT NULL,
  "password" character varying(255) NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles(
  "id" integer PRIMARY KEY NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  "name" character varying(255) NOT NULL,
  "avatar" character varying(255) NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS profiles;

DROP TABLE IF EXISTS accounts;

