-- +goose Up
CREATE TYPE skill_level AS ENUM(
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE IF NOT EXISTS personalization_options(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "account_id" integer NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  "roadmap_id" integer NOT NULL REFERENCES roadmaps(id) ON DELETE CASCADE,
  "daily_time_availability" interval NOT NULL,
  "total_duration" interval NOT NULL,
  "skill_level" skill_level NOT NULL,
  "additional_info" text NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS personalization_options;

DROP TYPE IF EXISTS skill_level;

