-- +goose Up
CREATE TABLE IF NOT EXISTS accounts(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(255) NOT NULL,
  "email" character varying(255) NOT NULL,
  "password" character varying(255) NOT NULL,
  "created_at" timestamp(0) without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp(0) without time zone DEFAULT now() NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS accounts;

