-- +goose Up
CREATE TABLE IF NOT EXISTS roadmaps(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "account_id" integer NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  "title" character varying(255) NOT NULL,
  "slug" character varying(255) NOT NULL,
  "description" text NOT NULL,
  "created_at" timestamp(0) without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp(0) without time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_roadmaps_account_id ON roadmaps(account_id);

CREATE INDEX idx_roadmaps_slug ON roadmaps(slug);

CREATE TABLE IF NOT EXISTS topics(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "roadmap_id" integer NOT NULL REFERENCES roadmaps(id) ON DELETE CASCADE,
  "parent_id" integer REFERENCES topics(id) ON DELETE CASCADE,
  "title" character varying(255) NOT NULL,
  "slug" character varying(255) NOT NULL,
  "description" text NOT NULL,
  "order" integer NOT NULL,
  "finished" boolean NOT NULL DEFAULT FALSE,
  "created_at" timestamp(0) without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp(0) without time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_topics_roadmap_id ON topics(roadmap_id);

CREATE INDEX idx_topics_parent_id ON topics(parent_id);

CREATE INDEX idx_topics_slug ON topics(slug);

-- +goose Down
DROP TABLE IF EXISTS topics;

DROP TABLE IF EXISTS roadmaps;

