-- +goose Up
CREATE TABLE IF NOT EXISTS identities(
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp(0) without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp(0) without time zone DEFAULT now() NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS identities;

